# ZMK Studio + combos on
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_COMBO=y

# Optional: more headroom for many hold-taps
CONFIG_ZMK_BEHAVIOR_HOLD_TAP_MAX_HELD=16
CONFIG_ZMK_BEHAVIOR_HOLD_TAP_MAX_CAPTURED_EVENTS=64
